server:
  port: 8040

spring:
  application:
    name: biz
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my_realm


logging:
  level:
    com.spring.keycloak: DEBUG