server:
  port: 8060

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: gateway
          uri: http://localhost:8040
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/my_realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/realms/my_realm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/realms/my_realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:8080/realms/my_realm/protocol/openid-connect/certs
        registration:
          my_client_a:
            provider: keycloak
            client-id: my_client_a
            client-secret: 5ssuqVTdq65TxhypH5ehv36xLUbETYeD
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
          my_client_b:
            provider: keycloak
            client-id: my_client_b
            client-secret: gsL7LolhARwxM0UezFtozOzuUwoR1KjH
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid



logging:
  level:
    org:
      springframework:
        security: DEBUG